SELECT TO_DATE(SAL.SAL_DT,'YYYY-MM-DD') SAL_DT, 
				SUM(SAL.SAL_CNT*PDT.PRICE) TOTAL_SAL
		
		FROM PRODUCT_TB PDT,
		  		SALE_TB SAL,
				STORE_TB STR
				
		WHERE STR.STO_ID = '11111' AND
				SAL.SAL_DT BETWEEN '2017-12-01' AND '2017-12-30' AND
				PDT.PDT_NO = SAL.PDT_NO AND
				STR.STO_ID = SAL.STO_ID
		
		GROUP BY TO_DATE(SAL.SAL_DT,'YYYY-MM-DD')
		ORDER BY SAL_DT ASC
		
		
		
		

		
		
		
		
		SELECT SAL.SAL_DT, 
				SUM(SAL.SAL_CNT*PDT.PRICE) TOTAL_SAL
		
		FROM PRODUCT_TB PDT,
		  		SALE_TB SAL,
				STORE_TB STR
				
		WHERE STR.STO_ID = '11111' AND
				SAL.SAL_DT BETWEEN '2017-12-01' AND '2017-12-30' AND
				PDT.PDT_NO = SAL.PDT_NO AND
				STR.STO_ID = SAL.STO_ID
		
		GROUP BY SAL.SAL_DT
		
		
		
		SELECT PDT.PDT_NO,
				PDT.PDT_GB,
				PDT.PDT_NM,
				PDT.PRICE,
				SAL.SAL_CNT
		
		FROM PRODUCT_TB PDT,
			  SALE_TB SAL,
				STORE_TB STR
				
		WHERE STR.STO_ID = '11111' AND
				TO_CHAR(SAL.SAL_DT,'yyyyMMdd') = TO_CHAR(sysdate,'yyyyMMdd') AND
				PDT.PDT_NO = SAL.PDT_NO AND
				STR.STO_ID = SAL.STO_ID
		
		
		
		
		
		
		
		
		
		
SELECT * FROM SALE_TB;








SELECT TO_CHAR(SAL.SAL_DT,'YYYY-MM-DD') SAL_DT, 
				SUM(SAL.SAL_CNT*PDT.PRICE) TOTAL_SAL
		
		FROM PRODUCT_TB PDT,
		  		SALE_TB SAL,
				STORE_TB STR
				
		WHERE STR.STO_ID = #{stoId} AND
				SAL.SAL_DT BETWEEN TO_DATE('2017-12-01','YYYY-MM-DD') 
				AND TO_DATE('2017-12-30','YYYY-MM-DD') AND
				PDT.PDT_NO = SAL.PDT_NO AND
				STR.STO_ID = SAL.STO_ID
		
		GROUP BY TO_CHAR(SAL.SAL_DT,'YYYY-MM-DD')
		ORDER BY SAL_DT ASC




